config/routes.rb
Rails.application.routes.draw do
  # 顧客用
  # URL //sign_in ...
  devise_for :users, controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  post 'users/guest_sign_in', to: 'public/users#guest_sign_in'

  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, controllers: {
    sessions: "admin/sessions"
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html


  scope module: :public do
    root 'homes#top'
    get 'homes/about', as: 'about'

    resources :users, only: [:show, :edit, :update, :destroy] do
      member do
        get :stats
        get :favourite_review
        get :favourite_bathhouses
        get :follow
        get :follower
        get :confirm
      end
    end

    resources :notices, only: [:index]

    resources :news, only: [:index, :show]

    resources :bathhouses, only: [:new, :create, :index, :show, :edit, :update] do
      member do
        get :reviews_index
        get :congestion_situation
        get :edit_image
        post :edit_confirm
        get :destroy_image
        get :review_new
      end
      collection do
        get :confirm
        get :image
        get :search
        post :create_confirm
      end
      resource :favourite_bathhouses, only: [:create, :destroy]
    end

    resources :comments, only: [:create, :destroy]

    resources :reports, only: [:new, :create]

    resources :reviews, only: [:index, :show, :create, :destroy] do
      resource :favourites, only: [:create, :destroy]
    end

  end

  namespace :admin do
    root 'homes#index'

    resources :categories, only: [:index]

    resources :features, only: [:index, :create, :destroy]

    resources :users, only: [:show, :edit, :update, :destroy] do
      member do
        get :stats
        get :favorite_bathhouses
        get :follow
        get :follower
        get :confirm
        get :warning_new
        get :warnings
      end
    end

    resources :warnings, only: [:create]

    resources :reports, only: [:index, :show]

    resources :news, only: [:new, :index, :show, :edit, :destroy]

    resources :bathhouses, only: [:index, :show, :edit, :update, :destroy] do
      member do
        get :reviews_index
        get :congestion_situation
        get :edit_image
        get :edit_confirm
        resources :destroy_image, only: [:destroy]
        resources :review, only: [:show]
      end
    end

    resources :reviews, only: [:index, :destroy]
  end


end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SpaMania</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %>
    <script src="https://kit.fontawesome.com/4f29079cc3.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css"/>
    <script src="https://code.jquery.com/jquery-3.6.1.js" integrity="sha256-3zlB5s2uwoUzrXK3BT7AX3FyvojsraNFxCc2vC/7pNI=" crossorigin="anonymous"></script>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%#= javascript_pack_tag 'application'%>
    <script type="text/javascript" src="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js"></script>




  </head>

  <body class="d-flex flex-column vh-100">
    <header class="shadow-sm">
      <nav class="navbar navbar-expand-lg navbar-light">
        <div class="container">
          <a class="navbar-brand" href="/">LOGO</a>
          <div class="collapse navbar-collapse flex-column">
            <ul class="navbar-nav ml-auto">
              <% if user_signed_in? %>
                <li class="nav-item">

                </li>
                <li class="nav-item">

                </li>
                <li class="nav-item">
                  <%= link_to "施設登録", confirm_bathhouses_path, class: 'nav-link text-dark mx-1' %>
                </li>
                <li class="nav-item">
                  <%= link_to "ログアウト", destroy_user_session_path, class: 'nav-link text-dark mx-1', method: :delete %>
                </li>
                <li class="nav-item">
                  <%= link_to user_path(current_user.id) do %>
                    <% if current_user.user_image.attached? %>
                      <div class="user-img-head m-1">
                        <%= image_tag current_user.user_image, class: "user-img" %>
                      </div>
                    <% else %>
                      <div class="user-img-head m-1">
                        <%= image_tag 'onsen_images.png', class: "user-img" %>
                      </div>
                    <% end %>
                  <% end %>
                </li>

              <% elsif admin_signed_in? %>
                <li class="nav-item">
                  <%= link_to "ジャンル一覧", admin_features_path, class: 'nav-link text-dark mx-1' %>
                </li>
                <li class="nav-item">

                </li>
                <li class="nav-item">

                </li>
                <li class="nav-item">

                </li>
                <li class="nav-item">
                  <%= link_to "ログアウト", destroy_admin_session_path, class: 'nav-link text-dark mx-1', method: :delete %>
                </li>

              <% else %>
                <li class="nav-item">
                  <%= link_to "About", about_path, class: 'nav-link text-dark mx-1' %>
                </li>
                <li class="nav-item">

                </li>
                <li class="nav-item">
                  <%= link_to "新規登録", new_user_registration_path, class: 'nav-link text-dark mx-1' %>
                </li>
                <li class="nav-item">
                  <%= link_to "ログイン", new_user_session_path, class: 'nav-link text-dark mx-1' %>
                </li>
              <% end %>
            </ul>
            <ul class="navbar-nav ml-auto">
              <li class="nav-item">
                <div class="input-group">
                  <%= link_to "施設を探す", bathhouses_path, class: 'nav-link text-dark mx-1',data: {"turbolinks"=>false} %>
                  <%= search_form_for @q, url: bathhouses_path do |f| %>
                    <div class="input-group">
                      <%= f.search_field :name_or_address_city_or_address_town_or_address_building_or_access_cont, class: "form-control", placeholder: "施設検索" %>
                      <%= f.submit '検索', class: "btn btn-outline-success", id: "button-addon2" %>
                    </div>
                  <% end %>
                </div>
              </li>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <%= render 'public/shared/flash_message' %>
    <%= yield %>
    <footer class="shadow-sm mt-auto py-3 border-top border-dark">
    </footer>

  </body>
</html>